<a href="https://colab.research.google.com/github/HoDoDuyDung/Colab_Code/blob/main/HoDoDuyDung_20146235_LungCancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
url = 'lung_cancer_examples.csv'
data = pd.read_csv(url)
data.head()

del data['Name']
del data['Surname']
data.head()

   Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [17]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

x = data.loc[:,['Age','Smokes','AreaQ','Alkhol']]
y = data.loc[:,['Result']]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

print(x_train,x_train_std)

    Age  Smokes  AreaQ  Alkhol
23   44       5      8       1
30   36      13      5       2
14   34      25      4       8
50   42      12      6       2
13   28      20      2       8
46   31      20      9       4
4    68       4      5       6
16   42      22      3       5
55   77      20      5       4
44   39      15      7       2
35   25      20      8       2
27   34      12      8       0
40   50      20      2       4
3    28       0      8       1
51   44      30      1       6
7    22      12      5       2
57   43      30      3       8
10   33       4      8       0
2    30       0      5       2
11   18      10      6       3
39   37      10      5       3
32   47      15      1       8
37   62      15      5       5
26   37      15      6       2
22   22      20      6       2
56   75      15      3       5
45   21      20      8       3
17   19      12      8       0
6    58      15     10       0
24   77       3      2       6
21   33       8      8       1
34   26      10      7       2
25   21      20      5       3
18   62       5      4       3
58   51      25      9       0
53   35      20      5       1
28   55      20      1       4
15   39      18      8       1
12   25       2      5       1
52   26      34      1       8
54   26      13      6       1 [[ 0.27596926 -1.2162497   1.05738659 -0.87073248]
 [-0.22138193 -0.22879945 -0.15811388 -0.4650503 ]
 [-0.34571973  1.25237593 -0.56328071  1.96904277]
 [ 0.15163146 -0.35223073  0.24705294 -0.4650503 ]
 [-0.71873312  0.63521952 -1.37361436  1.96904277]
 [-0.53222643  0.63521952  1.46255342  0.34631406]
 [ 1.76802283 -1.33968099 -0.15811388  1.15767841]
 [ 0.15163146  0.88208209 -0.96844753  0.75199623]
 [ 2.32754292  0.63521952 -0.15811388  0.34631406]
 [-0.03487524  0.01806311  0.65221977 -0.4650503 ]
 [-0.90523982  0.63521952  1.05738659 -0.4650503 ]
 [-0.34571973 -0.35223073  1.05738659 -1.27641466]
 [ 0.64898265  0.63521952 -1.37361436  0.34631406]
 [-0.71873312 -1.83340611  1.05738659 -0.87073248]
 [ 0.27596926  1.86953234 -1.77878118  1.15767841]
 [-1.09174652 -0.35223073 -0.15811388 -0.4650503 ]
 [ 0.21380036  1.86953234 -0.96844753  1.96904277]
 [-0.40788863 -1.33968099  1.05738659 -1.27641466]
 [-0.59439533 -1.83340611 -0.15811388 -0.4650503 ]
 [-1.34042211 -0.59909329  0.24705294 -0.05936812]
 [-0.15921303 -0.59909329 -0.15811388 -0.05936812]
 [ 0.46247596  0.01806311 -1.77878118  1.96904277]
 [ 1.39500944  0.01806311 -0.15811388  0.75199623]
 [-0.15921303  0.01806311  0.24705294 -0.4650503 ]
 [-1.09174652  0.63521952  0.24705294 -0.4650503 ]
 [ 2.20320513  0.01806311 -0.96844753  0.75199623]
 [-1.15391542  0.63521952  1.05738659 -0.05936812]
 [-1.27825321 -0.35223073  1.05738659 -1.27641466]
 [ 1.14633384  0.01806311  1.86772024 -1.27641466]
 [ 2.32754292 -1.46311227 -1.37361436  1.15767841]
 [-0.40788863 -0.84595586  1.05738659 -0.87073248]
 [-0.84307092 -0.59909329  0.65221977 -0.4650503 ]
 [-1.15391542  0.63521952 -0.15811388 -0.05936812]
 [ 1.39500944 -1.2162497  -0.56328071 -0.05936812]
 [ 0.71115155  1.25237593  1.46255342 -1.27641466]
 [-0.28355083  0.63521952 -0.15811388 -0.87073248]
 [ 0.95982715  0.63521952 -1.77878118  0.34631406]
 [-0.03487524  0.38835696  1.05738659 -0.87073248]
 [-0.90523982 -1.58654355 -0.15811388 -0.87073248]
 [-0.84307092  2.36325747 -1.77878118  1.96904277]
 [-0.84307092 -0.22879945  0.24705294 -0.87073248]]

In [18]:
model = Perceptron(max_iter = 1000, eta0=0.05,random_state = 0)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)
print('Đo chinh xac ma hinh chua scale:',accuracy_score(y_test,y_pred))

[1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 1]
    Result
29       1
8        0
36       1
42       1
48       1
31       1
1        1
43       1
49       1
33       1
0        1
19       1
9        1
38       0
47       0
41       0
5        0
20       1
Đo chinh xac ma hinh chua scale: 0.9444444444444444

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
model = Perceptron(max_iter = 1000, eta0 = 0.05,random_state = 0)
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac ma hinh chua scale:',accuracy_score(y_test,y_pred))

[1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1]
    Result
29       1
8        0
36       1
42       1
48       1
31       1
1        1
43       1
49       1
33       1
0        1
19       1
9        1
38       0
47       0
41       0
5        0
20       1
Do chinh xac ma hinh chua scale: 0.8888888888888888

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)